### ISSUE TITLE
Boolean inputs instead of String

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_dna#5]
Low priority issue.
Some of the biobb_canal properties (and maybe also in other biobb_dna bbs) should be changed from String to Boolean so that GUIs can use a switch.
Example:   

https://github.com/bioexcel/biobb_dna/blob/b2021557f4fe270b184b0360a1ceae7608ffa051/biobb_dna/curvesplus/biobb_canal.py#L34C12-L34C66

**Comment by gbayarri** [comment]
Fixed, it will be available in the next 4.2.3 release
