### ISSUE TITLE
Check properties and arguments

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_dna#6]
Low priority issue.
Check arguments and properties functions from biobb_common should be added in all bbs
Example:
```
        # Check the properties
        self.check_properties(properties)
        self.check_arguments()
```
Like in the biobb_amber bbs:
https://github.com/bioexcel/biobb_amber/blob/be51f8f42e23433a00f7308e28fc9b97786729c2/biobb_amber/ambpdb/amber_to_pdb.py#L74C1-L76C31

**Comment by gbayarri** [comment]
Fixed.
